services:
  - type: web
    name: tedx-auth-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn auth_api.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: tedx-db
          property: connectionString

      - key: ALLOWED_HOSTS
        value: ".onrender.com,api.yourdomain.com"

      - key: CORS_ALLOWED_ORIGINS
        value: "https://tedx-frontend.onrender.com,https://yourdomain.com"

      - key: PYTHONPATH
        value: "."

      # These need to be manually set in the Render Dashboard since sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: tedx-db
    databaseName: tedx
    user: tedx_user
    plan: free
