services:
  - type: web
    name: tedx-auth-api
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: tedx-db
          property: connectionString

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: CORS_ALLOWED_ORIGINS
        value: "https://tedx-frontend.onrender.com,https://yourdomain.com"

      - key: PYTHONPATH
        value: "."

      # Google OAuth Configuration (Required)
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

      # Production optimization
      - key: WEB_CONCURRENCY
        value: "3"

      # Optional: For emergency superuser creation in production
      # - key: SUPERUSER_CREATION_KEY
      #   sync: false

databases:
  - name: tedx-db
    databaseName: tedx
    user: tedx_user
    plan: free
